[tool.poetry]
name = "BankApp"
version = "0.1.0"
description = "Bank masking app"
authors = ["smedlu <zav80@mail.ru>"]
readme = "README.md"
packages = [{ include = "project_bankapp", from = "project_BankAPP/src" }]

[tool.poetry.dependencies]
python = "^3.14"

[tool.poetry.group.lint.dependencies]
flake8 = "^7.3.0"
mypy = "^1.0.0"
black = "^24.0.0"
isort = "^5.0.0"

[tool.black]
line-length = 119
target-version = ["py314"]
skip-string-normalization = false
exclude = '''
/(
  \.git
)/
'''

[tool.isort]
profile = "black"
line_length = 119
multi_line_output = 3

[tool.flake8]
max-line-length = 119
exclude = ["./.git", "./__pycache__"]
ignore = ["E402", "W503", "W504"]

[tool.mypy]
python_version = "3.14"
disallow_untyped_defs = true
warn_return_any = true
exclude = [
    "venv/",
]
show_error_codes = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"